language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

services:
  - docker

install:
  - cd java
  - mvn clean install
  - mvn verify

before_script:
  - docker-compose --version
  - docker ps -a -q
  - docker build serveur -t serveur
  - docker build moteur -t moteur
  - docker build client -t client
  - docker images

script:
  - docker-compose up --scale client=3
  #- docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
  #- docker-compose logs # affichage des logs
  # on efface tous les containers qui sont éteints puis les images
  - mvn failsafe:integration-test -Dit.test=client.src.test.FacadeJoueurITCase
  - mvn failsafe:integration-test -Dit.test=moteur.src.test.MoteurWebControlleurITCase
  - mvn failsafe:integration-test -Dit.test=serveur.src.test.ServeurITCase.getNbJoueurTest
  - mvn failsafe:integration-test -Dit.test=serveur.src.test.ServeurITCase.getNbPartieTest
  - mvn failsafe:integration-test -Dit.test=serveur.src.test.ServeurITCase.getStatsTest
  - mvn failsafe:integration-test -Dit.test=serveur.src.test.ServeurITCase.showPartieTest
  
  - docker rm $(docker ps -a -q)
  - docker ps -a -q
  - docker rmi serveur
  - docker rmi moteur
  - docker rmi client
