language: java

jdk:
  - openjdk11

services:
  - docker

script:
  - cd java
  - mvn install
  - docker build serveur -t jokr:serveur
  - docker build sevenw -t jokr:sevenw
  #- cd serveur
  - docker run -d --name statServeur -p 8081:8081 jokr:serveur
  #- docker start statServeur
  #- cd ../sevenw
  #- java -jar sevenw/target/sevenw-1.0-jar-with-dependencies.jar true 1 5 false http://127.0.0.1:8081 &
  #- java -jar sevenw/target/sevenw-1.0-jar-with-dependencies.jar false 20000 3 true http://127.0.0.1:8081
  - docker run -d --name sevenw1 -p 8081:8081 jokr:sevenw