language: java

jdk:
  - openjdk11


services:
  - docker


install:
  - cd java
  - mvn clean install -Dmaven.test.skip=true


before_script:
  - docker-compose --version
  - docker ps -a -q
  - docker build serveur -t serveur
  - docker build moteur -t moteur
  - docker images


script:
  - docker-compose up #--scale moteur=3
  #- docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
