language: java
jdk:
  - openjdk11
script:
  - cd java
  - mvn install
#  - cd commun
#  - mvn exec:java &
#  - cd ../serveur
  - java -jar serveur/target/serveur-1.0-jar-with-dependencies.jar
#  - mvn exec:java &
#  - cd ../sevenw
  - java -jar sevenw/target/sevenw-1.0-jar-with-dependencies.jar
#  - mvn exec:java