language: java

jdk:
  - openjdk11

services:
  - docker

script:
  - cd java
  - mvn install
  - docker build serveur -t serveur:stat
  - cd serveur
  - docker run -d --name statServeur -p 10.0.0.1:8081:8081 serveur:stat
  - docker start statServeur
  - cd ..
  #- java -jar serveur/target/serveur-1.0-jar-with-dependencies.jar &
  - java -jar sevenw/target/sevenw-1.0-jar-with-dependencies.jar true 1 5 false http://10.0.0.1:8081
  - java -jar sevenw/target/sevenw-1.0-jar-with-dependencies.jar false 20000 3 true http://10.0.0.1:8081