language: java

jdk:
  - openjdk11


services:
  - docker


install:
  - cd java
  - mvn install


before_script:
  - docker-compose --version
  - docker ps -a -q
  - docker build serveur -t serveur
  - docker build sevenw -t sevenw
  - docker images


script:
  - docker-compose up --scale client=3
  #- docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
