version: '3'

services:

  serveur:
    image: serveur
    networks:
      testing_net:
        ipv4_address: 10.0.0.253
    depends_on:
      - moteur
  
  
  moteur:
    image: moteur
    environment:
      - SERVER_IP=http://10.0.0.253:8081
    networks:
      testing_net:


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24