version: '3'

services:

  serveur:
    image: serveur
    networks:
      ci_net:
        ipv4_address: 10.0.0.253
    depends_on:
      - moteur

  moteur:
    image: moteur
    environment:
      - SERVER_IP=http://10.0.0.253:8081
    networks:
      ci_net:
        ipv4_address: 10.0.0.1

  client:
    image: client
    environment:
      - ENGINE_IP=http://10.0.0.1:8085
      - NAMES=(Jean Jacques George Philippe Ralph Jeremy Ossama Kevin MBappe JeanNeymar Mathilda Chloe Barbara Julia)
    networks:
      ci_net:
    depends_on:
      - moteur


networks:
  ci_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24