version: '3'


services:

  serveur:
    image: serveur
    container_name: serveur
    networks:
      testing_net:
        ipv4_address: 10.0.0.1
    depends_on:
      - sevenw
  

  sevenw:
    image: sevenw
    environment:
      - SERVER_IP=10.0.0.1
    networks:
      testing_net:
      


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24