version: '3'

services:

  serveur:
    image: serveur
    networks:
      ci_net:
        ipv4_address: 192.168.1.250

  moteur:
    image: moteur
    environment:
      - SERVER_IP=http://192.168.1.250:8080/
    networks:
      ci_net:
        ipv4_address: 192.168.1.240
    depends_on:
      - serveur

  client:
    image: client
    environment:
      - ENGINE_IP=http://192.168.1.240:8085/
    networks:
      ci_net:
    depends_on:
      - moteur


networks:
  ci_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
